[package]
name = "awijan"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4.3", features = ["derive"] }
octocrab = "0.23"
tokio = { version = "1.28", features = ["macros", "rt-multi-thread"] }
